In [60]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.1'

In [4]:
cfe_df = pd.read_csv("car_fuel_efficiency.csv")

In [5]:
cfe_df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [6]:
len(cfe_df)

9704

In [16]:
cfe_df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [18]:
len(cfe_df['fuel_type'].unique())

2

In [19]:
cfe_df.isna().any()

engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool

In [26]:
int(cfe_df.isna().any().sum())

4

In [32]:
cfe_df_asia = cfe_df[cfe_df['origin'] == 'Asia']
float(cfe_df_asia['fuel_efficiency_mpg'].max())

23.759122836520497

In [51]:
median_horsepower_before_fillna = cfe_df['horsepower'].median()
most_frequent_horsepower = cfe_df['horsepower'].value_counts().idxmax()

In [52]:
cfe_df_filled_na_horsepower = cfe_df['horsepower'].fillna(most_frequent_horsepower)
print(f"Median Horsepower before FillNA: {median_horsepower_before_fillna} and after: {cfe_df_filled_na_horsepower.median()}")

Median Horsepower before FillNA: 149.0 and after: 152.0


In [75]:
cfe_df_asia_subselect = cfe_df_asia[["vehicle_weight", "model_year"]]
X = cfe_df_asia_subselect[:7].to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [80]:
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [81]:
X_INV = np.linalg.inv(XTX)
X_INV

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [82]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [87]:
np.dot(np.dot(X_INV, X.T), y).sum()

np.float64(0.5187709081074016)